title: First Page
author: Wyland Crews
email: crews.wyland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My First GitHub page with Jekyll.

# social links
github_username:  wylandcrews # DO NOT include the @ character, or else the build will fail!
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
